package io.github.whazzabi.whazzup.business.github.common.api;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class GithubWorkflowRun {

    public Long id;
    public String name;
    public Long workflow_id;
    public String status;
    public String conclusion;
    public String url;
    public String html_url;
    public String head_branch;

    public String created_at;
    public String updated_at;
    public GithubWorkflowRunHeadCommit head_commit;

//{
//  "id": 905656094,
//  "name": "Terraform, Build, Test, Deploy",
//  "node_id": "WFR_lAHOBHz6Ws4TZOpCzjX7Nx4",
//  "head_branch": "master",
//  "head_sha": "9b8c03ade5671f54cec92bf1314759864f6b7224",
//  "run_number": 138,
//  "event": "push",
//  "status": "completed",
//  "conclusion": "success",
//  "workflow_id": 4594843,
//  "check_suite_id": 2909129853,
//  "check_suite_node_id": "MDEwOkNoZWNrU3VpdGUyOTA5MTI5ODUz",
//  "url": "https://api.github.com/repos/Egoditor/qrapp-legacy/actions/runs/905656094",
//  "html_url": "https://github.com/Egoditor/qrapp-legacy/actions/runs/905656094",
//  "pull_requests": [],
//  "created_at": "2021-06-04T08:39:38Z",
//  "updated_at": "2021-06-04T08:50:53Z",
//  "jobs_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/actions/runs/905656094/jobs",
//  "logs_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/actions/runs/905656094/logs",
//  "check_suite_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/check-suites/2909129853",
//  "artifacts_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/actions/runs/905656094/artifacts",
//  "cancel_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/actions/runs/905656094/cancel",
//  "rerun_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/actions/runs/905656094/rerun",
//  "workflow_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/actions/workflows/4594843",
//  "head_commit": {
//    "id": "9b8c03ade5671f54cec92bf1314759864f6b7224",
//    "tree_id": "a59de7658b16fd3872c22fb7e20b8b065ea6d05b",
//    "message": "Updating monitoring names",
//    "timestamp": "2021-06-04T08:39:30Z",
//    "author": {
//      "name": "sebastian.waschnick",
//      "email": "sebastian@waschnick.de"
//    },
//    "committer": {
//      "name": "sebastian.waschnick",
//      "email": "sebastian@waschnick.de"
//    }
//  },
//  "repository": {
//    "id": 325380674,
//    "node_id": "MDEwOlJlcG9zaXRvcnkzMjUzODA2NzQ=",
//    "name": "qrapp-legacy",
//    "full_name": "Egoditor/qrapp-legacy",
//    "private": true,
//    "owner": {
//      "login": "Egoditor",
//      "id": 75299418,
//      "node_id": "MDEyOk9yZ2FuaXphdGlvbjc1Mjk5NDE4",
//      "avatar_url": "https://avatars.githubusercontent.com/u/75299418?v=4",
//      "gravatar_id": "",
//      "url": "https://api.github.com/users/Egoditor",
//      "html_url": "https://github.com/Egoditor",
//      "followers_url": "https://api.github.com/users/Egoditor/followers",
//      "following_url": "https://api.github.com/users/Egoditor/following{/other_user}",
//      "gists_url": "https://api.github.com/users/Egoditor/gists{/gist_id}",
//      "starred_url": "https://api.github.com/users/Egoditor/starred{/owner}{/repo}",
//      "subscriptions_url": "https://api.github.com/users/Egoditor/subscriptions",
//      "organizations_url": "https://api.github.com/users/Egoditor/orgs",
//      "repos_url": "https://api.github.com/users/Egoditor/repos",
//      "events_url": "https://api.github.com/users/Egoditor/events{/privacy}",
//      "received_events_url": "https://api.github.com/users/Egoditor/received_events",
//      "type": "Organization",
//      "site_admin": false
//    },
//    "html_url": "https://github.com/Egoditor/qrapp-legacy",
//    "description": null,
//    "fork": false,
//    "url": "https://api.github.com/repos/Egoditor/qrapp-legacy",
//    "forks_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/forks",
//    "keys_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/keys{/key_id}",
//    "collaborators_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/collaborators{/collaborator}",
//    "teams_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/teams",
//    "hooks_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/hooks",
//    "issue_events_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/issues/events{/number}",
//    "events_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/events",
//    "assignees_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/assignees{/user}",
//    "branches_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/branches{/branch}",
//    "tags_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/tags",
//    "blobs_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/blobs{/sha}",
//    "git_tags_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/tags{/sha}",
//    "git_refs_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/refs{/sha}",
//    "trees_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/trees{/sha}",
//    "statuses_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/statuses/{sha}",
//    "languages_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/languages",
//    "stargazers_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/stargazers",
//    "contributors_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/contributors",
//    "subscribers_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/subscribers",
//    "subscription_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/subscription",
//    "commits_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/commits{/sha}",
//    "git_commits_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/commits{/sha}",
//    "comments_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/comments{/number}",
//    "issue_comment_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/issues/comments{/number}",
//    "contents_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/contents/{+path}",
//    "compare_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/compare/{base}...{head}",
//    "merges_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/merges",
//    "archive_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/{archive_format}{/ref}",
//    "downloads_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/downloads",
//    "issues_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/issues{/number}",
//    "pulls_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/pulls{/number}",
//    "milestones_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/milestones{/number}",
//    "notifications_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/notifications{?since,all,participating}",
//    "labels_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/labels{/name}",
//    "releases_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/releases{/id}",
//    "deployments_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/deployments"
//  },
//  "head_repository": {
//    "id": 325380674,
//    "node_id": "MDEwOlJlcG9zaXRvcnkzMjUzODA2NzQ=",
//    "name": "qrapp-legacy",
//    "full_name": "Egoditor/qrapp-legacy",
//    "private": true,
//    "owner": {
//      "login": "Egoditor",
//      "id": 75299418,
//      "node_id": "MDEyOk9yZ2FuaXphdGlvbjc1Mjk5NDE4",
//      "avatar_url": "https://avatars.githubusercontent.com/u/75299418?v=4",
//      "gravatar_id": "",
//      "url": "https://api.github.com/users/Egoditor",
//      "html_url": "https://github.com/Egoditor",
//      "followers_url": "https://api.github.com/users/Egoditor/followers",
//      "following_url": "https://api.github.com/users/Egoditor/following{/other_user}",
//      "gists_url": "https://api.github.com/users/Egoditor/gists{/gist_id}",
//      "starred_url": "https://api.github.com/users/Egoditor/starred{/owner}{/repo}",
//      "subscriptions_url": "https://api.github.com/users/Egoditor/subscriptions",
//      "organizations_url": "https://api.github.com/users/Egoditor/orgs",
//      "repos_url": "https://api.github.com/users/Egoditor/repos",
//      "events_url": "https://api.github.com/users/Egoditor/events{/privacy}",
//      "received_events_url": "https://api.github.com/users/Egoditor/received_events",
//      "type": "Organization",
//      "site_admin": false
//    },
//    "html_url": "https://github.com/Egoditor/qrapp-legacy",
//    "description": null,
//    "fork": false,
//    "url": "https://api.github.com/repos/Egoditor/qrapp-legacy",
//    "forks_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/forks",
//    "keys_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/keys{/key_id}",
//    "collaborators_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/collaborators{/collaborator}",
//    "teams_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/teams",
//    "hooks_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/hooks",
//    "issue_events_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/issues/events{/number}",
//    "events_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/events",
//    "assignees_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/assignees{/user}",
//    "branches_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/branches{/branch}",
//    "tags_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/tags",
//    "blobs_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/blobs{/sha}",
//    "git_tags_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/tags{/sha}",
//    "git_refs_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/refs{/sha}",
//    "trees_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/trees{/sha}",
//    "statuses_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/statuses/{sha}",
//    "languages_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/languages",
//    "stargazers_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/stargazers",
//    "contributors_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/contributors",
//    "subscribers_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/subscribers",
//    "subscription_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/subscription",
//    "commits_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/commits{/sha}",
//    "git_commits_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/git/commits{/sha}",
//    "comments_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/comments{/number}",
//    "issue_comment_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/issues/comments{/number}",
//    "contents_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/contents/{+path}",
//    "compare_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/compare/{base}...{head}",
//    "merges_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/merges",
//    "archive_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/{archive_format}{/ref}",
//    "downloads_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/downloads",
//    "issues_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/issues{/number}",
//    "pulls_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/pulls{/number}",
//    "milestones_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/milestones{/number}",
//    "notifications_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/notifications{?since,all,participating}",
//    "labels_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/labels{/name}",
//    "releases_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/releases{/id}",
//    "deployments_url": "https://api.github.com/repos/Egoditor/qrapp-legacy/deployments"
//  }
//},
}
